### ISSUE TITLE
the code of success plots on otb-2015 on the paper

### ISSUE THREAD

**Issue by iou1992** [lifeng9472/STRCF#1]
![default](https://user-images.githubusercontent.com/33022344/38135252-b87ff056-3449-11e8-972f-a8575877a38a.GIF)
thx advance

**Comment by iou1992** [comment]
the code of success plots on otb-2015 on the paper released？

**Comment by lifeng9472** [comment]
Hi, to generate the success plot curve on OTB-2015 dataset, you should download the existing OTB benchmark and follow the instructions. The link for the benchmark is here: http://cvlab.hanyang.ac.kr/tracker_benchmark/index.html
