### ISSUE TITLE
VOT数据集测试问题

### ISSUE THREAD

**Issue by jiangqb** [lifeng9472/STRCF#11]
请问除了上述 1.修改相对路径为绝对路径；2.更改STRCF路径之外还需要做什么操作呢？拷贝tracker_DeepSTRCF.m到vot-toolkit中也不能够正常运行。需要怎么做才能在VOT数据集上跑起来呢？非常感谢：）

**Comment by lifeng9472** [comment]
这个需要配置VOT的环境。你现在出的是什么错误呢？另外，我们也参加了VOT-2018的竞赛，性能比github上公布的结果也能高出不少。他们官网最近也会release最新的代码，有兴趣可以关注下。

**Comment by jiangqb** [comment]
VOT环境我也经配置好啦，可以正常跑测试NCC代码以及ECO代码等，但是我不知道您这个还需要怎么操作才可以在VOT上跑起来
![image](https://user-images.githubusercontent.com/19526796/47075864-ffb2bd80-d22f-11e8-9029-ffb227431685.png)

**Comment by lifeng9472** [comment]
了解了~，我这个版本的代码是跑在老版本的VOT-2016 toolkit上，当时并没有用trax这个协议。

**Comment by jiangqb** [comment]
啊 Σ( ° △ °|||) 原来是这样子，您方便发我一份老版本的toolkit吗？jqianbo@163.com，真是麻烦您啦

**Comment by lifeng9472** [comment]
已发。
