### ISSUE TITLE
subproblem f

### ISSUE THREAD

**Issue by cy3579** [lifeng9472/STRCF#16]
论文q中表述为gamma*g-gamma*h，但是代码中-(1/(gamma + mu))* (bsxfun(@times, model_xf, Shx_f)) +(gamma/(gamma + mu))* (bsxfun(@times, model_xf, Sgx_f))，h开头没有*gamma，这是为什么？

**Comment by chenfsjz** [comment]
@pupupupupu 我在看代码的时候也发现了这个问题,请问你最后确定了这个问题了吧!论文中的求导结果是没错的,那么应该是代码这里h部分缺少了gamma
