### ISSUE TITLE
the problem of cur_AUC？

### ISSUE THREAD

**Issue by iou1992** [lifeng9472/STRCF#6]
After the improvement of video = 'Human3', cur_AUC becomes smaller, can it represent improvement failure?
thx advance.

**Comment by lifeng9472** [comment]
Actually, in the latest version, I just change the computation of sub-problem g from GPU to CPU mode. So if there exists differences with the previous versions, there should be the roundoff error between CPU and GPU computation. It won't make much difference.

**Comment by iou1992** [comment]
ok,thanks.
